<?php
declare(strict_types=1);

// Argentofx SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ArgentofxUtility::setRegistrar(function (ArgentofxUtility $u): void {
    $u->clean = [ArgentofxClean::class, 'call'];
    $u->done = [ArgentofxDone::class, 'call'];
    $u->make_error = [ArgentofxMakeError::class, 'call'];
    $u->feature_add = [ArgentofxFeatureAdd::class, 'call'];
    $u->feature_hook = [ArgentofxFeatureHook::class, 'call'];
    $u->feature_init = [ArgentofxFeatureInit::class, 'call'];
    $u->fetcher = [ArgentofxFetcher::class, 'call'];
    $u->make_fetch_def = [ArgentofxMakeFetchDef::class, 'call'];
    $u->make_context = [ArgentofxMakeContext::class, 'call'];
    $u->make_options = [ArgentofxMakeOptions::class, 'call'];
    $u->make_request = [ArgentofxMakeRequest::class, 'call'];
    $u->make_response = [ArgentofxMakeResponse::class, 'call'];
    $u->make_result = [ArgentofxMakeResult::class, 'call'];
    $u->make_point = [ArgentofxMakePoint::class, 'call'];
    $u->make_spec = [ArgentofxMakeSpec::class, 'call'];
    $u->make_url = [ArgentofxMakeUrl::class, 'call'];
    $u->param = [ArgentofxParam::class, 'call'];
    $u->prepare_auth = [ArgentofxPrepareAuth::class, 'call'];
    $u->prepare_body = [ArgentofxPrepareBody::class, 'call'];
    $u->prepare_headers = [ArgentofxPrepareHeaders::class, 'call'];
    $u->prepare_method = [ArgentofxPrepareMethod::class, 'call'];
    $u->prepare_params = [ArgentofxPrepareParams::class, 'call'];
    $u->prepare_path = [ArgentofxPreparePath::class, 'call'];
    $u->prepare_query = [ArgentofxPrepareQuery::class, 'call'];
    $u->graphql_body = [ArgentofxGraphql::class, 'body'];
    $u->graphql_errors = [ArgentofxGraphql::class, 'errors'];
    $u->result_basic = [ArgentofxResultBasic::class, 'call'];
    $u->result_body = [ArgentofxResultBody::class, 'call'];
    $u->result_headers = [ArgentofxResultHeaders::class, 'call'];
    $u->transform_request = [ArgentofxTransformRequest::class, 'call'];
    $u->transform_response = [ArgentofxTransformResponse::class, 'call'];
});
